### ISSUE TITLE
suggestion: Use `&[u8]` instead of `&Vec<u8>`

### ISSUE THREAD

**Issue by xoac** [LouisGariepy/cornucopia#36]
I think that `&[u8]` for `BYTEA` as input parameter would be much more flexible for user of this library.

- It's common that you have functions similar to `as_bytes() -> &[u8]`: 
- There is also clippy lint for it: https://rust-lang.github.io/rust-clippy/master/index.html#ptr_arg

**Comment by LouisGariepy** [comment]
Hi @xoac, thanks for opening this issue.

Good catch! This is an easy fix, should be released in a few hours.

Cheers!

**Comment by LouisGariepy** [comment]
@xoac fixed in release 0.7.3!
